services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=${BACKEND_DATABASE_URL}
      - PORT=${BACKEND_PORT}
      - GOOGLE_CLIENT_ID=${BACKEND_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${BACKEND_GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_REDIRECT_URI=${BACKEND_GOOGLE_CLIENT_REDIRECT_URI}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
      - JWT_ISS=${BACKEND_JWT_ISS}
      - ACCESS_TOKEN_EXP=${BACKEND_ACCESS_TOKEN_EXP}
      - REFRESH_TOKEN_EXP=${BACKEND_REFRESH_TOKEN_EXP}
      - TIMEOUT=${BACKEND_TIMEOUT}
    volumes:
      - .:/app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres

volumes:
  postgres-volume:
  pgadmin-volume:
