services:
  auth:
    container_name: auth
    image: supabase/auth:v2.177.0
    ports:
      - 9999:9999
      - 9100:9100
    env_file:
      - .env.auth
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: database
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      - ./init_postgres.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      DB_NAMESPACE: auth
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  database:
